### ISSUE TITLE
Running applets in new versions of Intellij Idea

### ISSUE THREAD

**Issue by ingotr** [WiMank/Robert-Lafore-Examples#2]
Hello! Thank you for awesome work.
I think you should interesing to adding this info about
runnig applet in new version of Intellij Idea.

For succesed run user should dowload and install Java Applet Support plugin from Jetbrains:
https://plugins.jetbrains.com/plugin/13148-java-applets-support/versions

And then they could use your instructions from Readme.md

**Comment by WiMank** [comment]
Done
